---
- name: Installs tmux
  apt: 
    pkg=tmux 
    state=present

- name: Adds .tmux.conf for all accounts for detected version
  template: 
    src: tmux.conf.j2
    dest: "~{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: tmux_users

